#!/usr/local/bin/perl -w
use strict;
use Mariachi;

my $input = shift || die "need an input maildir";
my $output = shift || die "where do we put them?";
my $mariachi = Mariachi->new( input  => $input,
                              output => $output,
                            );

$mariachi->perform;
